services:
  db:
    image: postgres:17.5
    container_name: shortener_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shortener_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pg-url-shortener
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  db_data:

